config/routes.rb
Hotel_Advisor::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :users
  resources :hotels do
    collection do
      get 'best'
    end
  end
  resources :comments
  root :to => 'hotels#best'
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :hotel
  validates :country, :state, :city, :street, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :hotel
  has_one :rate
end

app/models/hotel.rb
require 'carrierwave/orm/activerecord'
class Hotel < ActiveRecord::Base
  mount_uploader :photo, HotelPhotoUploader
  belongs_to :user
  has_one :address
  has_many :comments
  accepts_nested_attributes_for :address
  letsrate_rateable "stars"
  validates :title, presence: true, uniqueness: true
  validates :price, numericality: true
  validates :room_description, length: { minimum: 20 }
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  belongs_to :comment

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :hotels
  has_many :comments
  letsrate_rater
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new comment_params
    @comment.save
    redirect_to @comment.hotel
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :hotel_id)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_hotel, only: [:show]

  def index
    @hotels = Hotel.all
  end

  def best
    @rate = RatingCache.order(avg: :desc).limit(5)
  end

  def new
    @hotel = current_user.hotels.new
    @hotel.build_address
  end

  def create
    @hotel = current_user.hotels.new hotel_params
    if @hotel.save
      redirect_to @hotel
    else
      render action: 'new'
    end
  end

  def show
    @comment = current_user.comments.build
  end

  private

  def hotel_params
    params.require(:hotel).permit(:title, :breakfast_included, :room_description, :photo, :price, address_attributes: [:country, :state, :city, :street]) #add adress attribute
  end

  def find_hotel
    @hotel = Hotel.find params[:id]
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_i, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_item(name, url)
    if @active_menu_item == name.downcase.to_sym || current_page?(url)
      opt = { class: 'active' }
    end
    content_tag :li, opt do
      link_to name, url
    end
  end
end

app/views/hotels/best.html.slim
.span12
  - @rate.each do |rate|
    - hotel = Hotel.find(rate.cacheable_id)
    .hotel_block.span12
      .photo
        = image_tag hotel.photo, height: '150', width: '200' if hotel.photo.file
      .description    
        dl.dl-horizontal
          dt Hotel name
          dd 
            = hotel.title
          dt Rating
          dd 
            = rating_for hotel, "stars"
          dt Address
          dd 
            = hotel.address.country
            | ,   
            = hotel.address.state
            | , 
            = hotel.address.city
            | , 
            = hotel.address.street
          dt Room description
          dd 
            = hotel.room_description
          dt Breakfast included
          dd 
            - if hotel.breakfast_included
              |yes
            - else
              |no
          dt Price
          dd 
            = hotel.price
          dt  
            = link_to 'Details', hotel_path(hotel)

app/views/hotels/index.html.slim
- @hotels.each do |hotel|
  .hotel_block.span12
    .photo
      = image_tag hotel.photo, height: '150', width: '200' if hotel.photo.file
    .description    
      dl.dl-horizontal
        dt Hotel name
        dd 
          = hotel.title
        dt Rating
        dd 
          = rating_for hotel, "stars"
        dt Address
        dd 
          = hotel.address.country
          | ,   
          = hotel.address.state
          | , 
          = hotel.address.city
          | , 
          = hotel.address.street
        dt Room description
        dd 
          = hotel.room_description
        dt Breakfast included
        dd 
          - if hotel.breakfast_included
            |yes
          - else
            |no
        dt Price
        dd 
          = hotel.price
        dt  
          = link_to 'Details', hotel_path(hotel)

app/views/hotels/new.html.slim
h1 New hotel
= simple_form_for @hotel, html: {class: 'form-horizontal hotels_form'} do |f|
  .form-group
    = f.label :title, class: 'col-sm-3 control-label'
    .col-sm-9
      = f.input_field :title, class: 'form-control'
  .form-group
    = f.label :room_description, class: 'col-sm-3 control-label'
    .col-sm-9
      = f.input_field :room_description, as: :text, class: 'form-control'
  .form-group
    = f.label :photo, class: 'col-sm-3 control-label'
    .col-sm-9
      = f.file_field :photo
  .form-group
    = f.label :price, class: 'col-sm-3 control-label'
    .col-sm-9
      = f.input_field :price, class: 'form-control price'
  .form-group
    .col-sm-offset-3.col-sm-9.breakfast_included
      = f.input_field :breakfast_included, as: :boolean
      = f.label :breakfast_included

  h4 Hotel address

  = f.simple_fields_for :address do |af|
    .form-group
      = af.label :country, class: 'col-sm-3 control-label'
      .col-sm-9
        = af.input_field :country, as: :string, class: 'form-control'
    .form-group
      = af.label :state, class: 'col-sm-3 control-label'
      .col-sm-9
        = af.input_field :state, class: 'form-control'
    .form-group
      = af.label :city, class: 'col-sm-3 control-label'
      .col-sm-9
        = af.input_field :city, class: 'form-control'
    .form-group
      = af.label :street, class: 'col-sm-3 control-label'
      .col-sm-9
        = af.input_field :street, class: 'form-control'

  div.form-group
    div.col-sm-offset-2.col-sm-10
      = f.button :submit, class: 'btn btn-default'

app/views/hotels/show.html.slim
.hotel_show.span12
  h3 = @hotel.title
  p 
    = @hotel.address.country
    | ,   
    = @hotel.address.state
    | , 
    = @hotel.address.city
    | , 
    = @hotel.address.street
  - if @hotel.photo.file
    .span6.photo_show
      = image_tag @hotel.photo, height: '300', width: '400'  
  .span6.description_show
    dl.dl-horizontal      
      dt Room description
      dd =@hotel.room_description
      dt Price
      dd = @hotel.price
      dt Breakfast included
      dd 
        - if @hotel.breakfast_included
          |yes
        - else
          |no
  .rate.span12 
    = rating_for @hotel, "stars"
  = simple_form_for @comment, html: {class: 'form-horizontal comment_form'} do |f|
    = f.input_field :content, as: :text, class: 'form-control'
    = f.input_field :user_id, as: :hidden, value: current_user.id, class: 'form-control'
    = f.input_field :hotel_id, as: :hidden, value: @hotel.id, class: 'form-control'
    = f.button :submit, 'Comment', class: 'btn btn-default'

  .comments.span6
    - @hotel.comments.each do |comment|
      - rate = Rate.where("rater_id = ? AND rateable_id = ?", comment.user.id, @hotel.id).first
      .span3.email = comment.user.email
      .span3.comment_rate = rating_for @hotel, "stars", :star => rate.stars if rate
      .span6.comment_content = comment.content
      hr

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hotel</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= menu_item 'List of the hotels', hotels_path %></li>
          <li><%= menu_item 'Best Hotels', best_hotels_path %></li>
        <% end %>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <%if user_signed_in? %>
          <li><%= menu_item 'Add Hotel', new_hotel_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>   
        <% else %>
          <li><%= menu_item 'Sign in', new_user_session_path %></li>
          <li><%= menu_item 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>